### ISSUE TITLE
Esim profiles

### ISSUE THREAD

**Issue by flixerator** [damonto/telegram-sms#11]
Hi, very interesting project, thanks for the release, had a few questions as I am a beginner. I understand correctly that this project can be used to manage esim profiles of cards like 5ber, esim.me or ESTK.me on Qualcomm 410 WiFi Dongle? Because in github lpac wrote that it does not support AT+CCHO, AT+CGLA, and AT+CCHC commands and therefore does not support loading and managing profiles. Also is there an option to get a more detailed readme from you to understand how it is implemented? I'm currently writing a shell for this modem and would like to include there the implementation of remote installation and changing sim profiles, and found a hint of information only from you. Thanks in advance for the answer :)

Sorry, but don't know where to write this, so wrote into issues.

**Comment by damonto** [comment]
On 410 Wi-Fi Dongle you can use the QMI driver to manage your eSIM profiles
